version: '3.8'

services:
  app:
    build: .
    ports:
      - "443:443"  # HTTPS
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - mysql-data-hse:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql-data-hse:
